---
- name: Install Chocolatey and Notepad++ on Windows
  hosts: windows
  gather_facts: no
  vars:
    ansible_connection: winrm
    ansible_winrm_transport: ntlm
    ansible_port: 5985
    ansible_winrm_server_cert_validation: ignore

  tasks:
    - name: Ensure Chocolatey itself is installed
      ansible.windows.win_chocolatey:
        name: chocolatey
        state: present

    - name: Ensure Notepad++ is installed
      ansible.windows.win_chocolatey:
        name: notepadplusplus
        state: present

    - name: Verify installation
      ansible.windows.win_command: 'cmd /c "notepad++ -?"'
      register: notepadpp_version
      ignore_errors: yes

    - name: Show Notepad++ version
      ansible.builtin.debug:
        var: notepadpp_version.stdout
