---
- name: Install Chocolatey and Notepad++ on Windows
  hosts: windows
  gather_facts: no
  collections:
    - ansible.windows
  vars:
    ansible_connection: winrm
    ansible_winrm_transport: ntlm
    ansible_port: 5985
    ansible_winrm_server_cert_validation: ignore

  tasks:
    - name: Ensure Chocolatey itself is installed
      win_chocolatey:
        name: chocolatey
        state: present

    - name: Ensure Notepad++ is installed
      win_chocolatey:
        name: notepadplusplus
        state: present
