- name: Test the Credentials
- hosts: all
  gather_facts: no
  tasks:
    - debug:
        msg:
          - "Login: {{ production_login | default('undefined') }}"
          - "Password length: {{ production_password | default('undefined') | length }}"
